# Generated by Django 5.0.3 on 2024-05-27 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_postcategory_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
